export const URL_CONSTANTS = {
  REGISTER: "/api/v1/auth/register",
  LOGIN: "/api/v1/auth/login",
  ME: "/api/v1/auth/me",
  CHANGE_PASSWORD: "/api/v1/auth/change-password",
  FORGOT_PASSWORD: "/api/v1/auth/forgot",
  RESET_PASSWORD: "/api/v1/auth/reset",
  GENERATE_UPLOAD_URL: "/api/v1/videos/generate-upload-url",
  UPLOAD_COMPLETE: "/api/v1/videos/upload-complete",
  UPLOAD_RESUME_CHECK: "/api/v1/videos/uploads/check",
  UPLOADS_CLEAR: "/api/v1/videos/uploads/clear",
  GET_USER_VIDEOS: "/api/v1/videos/user",
  GET_VIDEO: "/api/v1/videos",
  FEEDBACK_SUBMIT: "/api/v1/feedback",
  LCJ_LINK_STATUS: "/api/v1/lcj/link-status",
  LCJ_LINK: "/api/v1/lcj/link",
  LCJ_UNLINK: "/api/v1/lcj/unlink",
  LCJ_VERIFY_LIVER: "/api/v1/lcj/verify-liver",
};
