FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgomp1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Copy từ worker folder
COPY worker/batch/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY worker/batch/ /app/batch/
COPY worker/shared/ /app/shared/

ENV PYTHONPATH=/app

WORKDIR /app/batch

CMD ["python", "process_video.py"]
