"""create video_product_exposures table for product timeline detection

Revision ID: 20260221_product_exposures
Revises: 20260221_add_step_progress_to_videos
Create Date: 2026-02-21 12:00:00.000000
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260221_product_exposures"
down_revision = "20260221_step_progress"
branch_labels = None
depends_on = None


def upgrade():
    # =========================================================
    # video_product_exposures
    # Stores AI-detected (and human-corrected) product exposure
    # segments on the video timeline.
    # Each row = one continuous segment where a product is shown.
    # =========================================================
    op.create_table(
        "video_product_exposures",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("video_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),

        # Product identification
        sa.Column("product_name", sa.Text(), nullable=False),
        sa.Column("brand_name", sa.Text(), nullable=True),
        sa.Column("product_image_url", sa.Text(), nullable=True),

        # Timeline segment (seconds from video start)
        sa.Column("time_start", sa.Float(), nullable=False),
        sa.Column("time_end", sa.Float(), nullable=False),

        # AI confidence (0.0 - 1.0)
        sa.Column("confidence", sa.Float(), nullable=True, server_default="0.8"),

        # Whether this row was generated by AI or manually edited
        # 'ai' = AI-generated, 'human' = human-edited/created
        sa.Column("source", sa.String(20), nullable=False, server_default="ai"),

        # Timestamps
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), onupdate=sa.func.now()),
    )

    # Indexes for fast lookup
    op.create_index(
        "ix_vpe_video_id",
        "video_product_exposures",
        ["video_id"],
    )
    op.create_index(
        "ix_vpe_video_time",
        "video_product_exposures",
        ["video_id", "time_start", "time_end"],
    )


def downgrade():
    op.drop_index("ix_vpe_video_time", table_name="video_product_exposures")
    op.drop_index("ix_vpe_video_id", table_name="video_product_exposures")
    op.drop_table("video_product_exposures")
